export const carosalFirst=[
    {
        id:0,
        banner:require('../../assets/png/banner.png')
    },
    {
        id:1,
        banner:require('../../assets/png/banner.png')
    }
]
export const carosalThree=[
    {
        id:0,
        banner:require('../../assets/video/img1.jpg')
    },
    {
        id:1,
        banner:require('../../assets/video/img2.jpg')
    },
    {
        id:2,
        banner:require('../../assets/video/img3.jpg')
    },
]


export const carousalTwo=[
    {
        id:0,
        image:require('../../assets/speaker/img1.png')
    },
    {
        id:1,
        image:require('../../assets/speaker/img2.png')
    },
    {
        id:2,
        image:require('../../assets/speaker/img3.png')
    },
    {
        id:3,
        image:require('../../assets/speaker/img4.png')
    },
    {
        id:4,
        image:require('../../assets/speaker/img5.png')
    },
    {
        id:5,
        image:require('../../assets/speaker/img6.png')
    },
    {
        id:6,
        image:require('../../assets/speaker/img7.png')
    },
    {
        id:7,
        image:require('../../assets/speaker/img8.png')
    },
    {
        id:8,
        image:require('../../assets/speaker/img9.png')
    },
    {
        id:9,
        image:require('../../assets/speaker/img10.png')
    },
    {
        id:10,
        image:require('../../assets/speaker/img11.png')
    },
    {
        id:11,
        image:require('../../assets/speaker/img12.png')
    },
    {
        id:12,
        image:require('../../assets/speaker/img1.png')
    },
]